### ISSUE TITLE
flush needed to output "ICEPACK COMPLETE" on OSX gnu compiler

### ISSUE THREAD

**Issue by cmbitz** [icepack/icepack#107]
When I compiled with netcdf, I had to add a 
flush(nu_diag)
at the end of the program icedrv, otherwise I didn't get the last output written to the log file, including the ICEPACK COMPLETED statement, the stdio would echo "ICEPACK run did not complete". 

I tried making it a 
call icepack_warnings_flush(nu_diag)
but it didn't work

I'm using my macbook pro with Monterey OSX and gnu compiler. I didn't have this problem until I compiled with netcdf. 
Otherwise all is well getting it to run on my laptop. Thanks, Cecilia Bitz

**Comment by danshapero** [comment]
Hi Cecilia, and greetings from APL! There is a bit of a name collision between this package, which is a glacier flow model, and [this package](https://github.com/CICE-Consortium/Icepack), which is a sea ice column physics model. I'm guessing you meant the latter. This hasn't been a problem before so we've mostly ignored it. I'll close this issue but if you ever decide you want to do some modeling of land ice then please give us a holler :D
