### ISSUE TITLE
Questions about the exact equation in the Synthetic ice stream (xy) case

### ISSUE THREAD

**Issue by ypzpy** [icepack/icepack#111]
Hi, may I ask what will be the exact equation to generate the data in the tutorial of Synthetic ice stream (xy) case?

**Comment by danshapero** [comment]
Sorry for the slow reply, I've been off work for a bit. The input fields for that problem are purely synthetic data that I made up through trial and error. The idea is to start from some simple but possibly un-physical initial state -- like a linearly sloping ice thickness -- and iterate towards a more physically realistic equilibrium. The values that I used are roughly similar to those of real ice streams in Antarctica although the geometry is very idealized. You can see more examples in the [book](https://doi.org/10.1007/978-3-642-03415-2) by Greve and Blatter.

I'll mark this as closed, but if you have more questions feel free to reopen. Alternatively, you can join the [Firedrake slack workspace](http://firedrakeproject.org/contact.html), where we have an icepack channel. Some of the other users might be able to answer your questions faster than I can.
