### ISSUE TITLE
Passing rate factor calculated from temperature back into 2D flow solver

### ISSUE THREAD

**Issue by megr090** [icepack/icepack#112]
I'm trying to implement the HeatTransport3D module to update the fluidity based on ice temperature in the 2D ice shelf example. Since the heat transport module requires a 3D mesh, I've been using the extruded mesh to calculate temperature and then trying to depth average and pass the depth averaged temperature into icepack.rate_factor to update A. However, I'm getting an error related to (I believe) the data type when passing the updated fluidity into the flow solver. 

Code:
```
flow_model = icepack.models.IceShelf()
flow_solver = icepack.solvers.FlowSolver(flow_model, dirichlet_ids=[1])

T = firedrake.Constant(255.15)
A = icepack.rate_factor(T)

h = h0.copy(deepcopy=True)
u = flow_solver.diagnostic_solve(
    velocity=u0,
    thickness=h,
    fluidity=A,
)

mesh3d = firedrake.ExtrudedMesh(mesh, layers=1)
Q0 = firedrake.FunctionSpace(mesh3d, family='CG', degree=2, vfamily='DG', vdegree=0)
V0 = firedrake.VectorFunctionSpace(mesh3d, dim=2, family='CG', degree=2, vfamily='GL', vdegree=0)
Q2 = firedrake.FunctionSpace(mesh3d, family='CG', degree=2, vfamily='GL', vdegree=4)

heat_transport = icepack.models.HeatTransport3D()
heat_solver = icepack.solvers.HeatTransportSolver(heat_transport)

E_expr = heat_transport.energy_density(firedrake.Constant(253.0), firedrake.Constant(0.0))
E = firedrake.interpolate(E_expr, Q2)
E_init = E.copy(deepcopy=True)

final_time = 400.
num_timesteps = 200
dt = final_time / num_timesteps
a = firedrake.Constant(0.0)

W = firedrake.FunctionSpace(mesh3d, family='DG', degree=2 - 1, vfamily='GL', vdegree=1)
x, y, ζ = firedrake.SpatialCoordinate(mesh3d)

for step in tqdm.trange(num_timesteps):
    h = flow_solver.prognostic_solve(
        dt,
        thickness=h,
        velocity=u,
        accumulation=a,
        thickness_inflow=h0,
    )

    T0 = heat_transport.temperature(E)
    T = firedrake.Function(Q2)
    T.project(T0)
    T2 = icepack.depth_average(T)
    A = firedrake.project(icepack.rate_factor(T2),Q)

    u = flow_solver.diagnostic_solve(
        velocity=u,
        thickness=h,
        fluidity=A,
    )

    # elevate to 3D
    U = u.dat.data_ro[:]
    S = s.dat.data_ro[:]
    H = h.dat.data_ro[:]

    u2 = firedrake.Function(V0)
    s2 = firedrake.Function(Q0)
    h2 = firedrake.Function(Q0)

    u2.dat.data[:] = U
    s2.dat.data[:] = S
    h2.dat.data[:] = H

    # calculate vertical velocity
    ω_expr = -(u2[0].dx(0) + u2[1].dx(1)) / h2 * ζ
    ω = firedrake.project(ω_expr, W)
    w = firedrake.interpolate(h2 * ω, W)

    # calculate heating rate
    ε_x, ε_z = horizontal_strain_rate(velocity=u2, surface=s2, thickness=h2), vertical_strain_rate(velocity=u2,
                                                                                                   thickness=h2)
    τ_x, τ_z = stresses(strain_rate_x=ε_x, strain_rate_z=ε_z, fluidity=A)
    q = inner(τ_x, ε_x) + inner(τ_z, ε_z)
    qm = firedrake.interpolate(q, Q2)

    # evolve energy density
    E = heat_solver.solve(
        dt,
        energy=E,
        velocity=u2,
        vertical_velocity=w,
        thickness=h2,
        energy_inflow=E_init,
        energy_surface=E_init,
        heat=qm,
        heat_bed=firedrake.Constant(0.0),
    )
```

Error:

> Traceback (most recent call last):
  File "/firedrake/src/firedrake/firedrake/function.py", line 452, in __float__
    raise ValueError("Can only cast scalar 'Real' Functions to float.")
ValueError: Can only cast scalar 'Real' Functions to float.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/firedrake/src/PyOP2/pyop2/utils.py", line 237, in verify_reshape
    a = np.asarray(data, dtype=t)
ValueError: setting an array element with a sequence.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/firedrake/src/firedrake/firedrake/constant.py", line 148, in assign
    self.dat.data = value
  File "/firedrake/src/PyOP2/pyop2/types/glob.py", line 136, in data
    self._data[:] = utils.verify_reshape(value, self.dtype, self.dim)
  File "/firedrake/src/PyOP2/pyop2/utils.py", line 239, in verify_reshape
    raise DataValueError("Invalid data: cannot convert to %s!" % dtype)
pyop2.exceptions.DataValueError: Invalid data: cannot convert to float64!

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/firedrake/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-fd3819d063d2>", line 1, in <module>
    runfile('/CDM_Model/230525_ImplementHeatTransport_IceShelf_2D_TwoWayCoupling.py', wdir='/CDM_Model')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/CDM_Model/230525_ImplementHeatTransport_IceShelf_2D_TwoWayCoupling.py", line 153, in <module>
    u = flow_solver.diagnostic_solve(
  File "/firedrake/src/icepack/icepack/solvers/flow_solver.py", line 138, in diagnostic_solve
    return self._diagnostic_solver.solve(**kwargs)
  File "/firedrake/src/icepack/icepack/solvers/flow_solver.py", line 213, in solve
    self._fields[name].assign(field)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/firedrake/src/firedrake/firedrake/adjoint/constant.py", line 50, in wrapper
    ret = assign(self, *args, **kwargs)
  File "/firedrake/src/firedrake/firedrake/constant.py", line 151, in assign
    raise ValueError(e)
ValueError: Invalid data: cannot convert to float64!

**Comment by danshapero** [comment]
Hi Meghana, thanks for reporting this! Are you able to attach the complete runnable script? I'll have an easier time getting you a fix if I can try it myself.

**Comment by megr090** [comment]
Thanks so much! I've attached the script (as a text file). 
[230525_ImplementHeatTransport_IceShelf_2D_TwoWayCoupling.txt](https://github.com/icepack/icepack/files/11602969/230525_ImplementHeatTransport_IceShelf_2D_TwoWayCoupling.txt)
