### ISSUE TITLE
pip3 fails to install ROL

### ISSUE THREAD

**Issue by bearecinos** [icepack/icepack#114]
Hi, 

I’m trying to install ROL so I can use the data assimilation capabilities of [icepack](https://github.com/icepack/icepack/blob/master/icepack/statistics.py#L78) but I haven't being able to install this even from [source](https://bitbucket.org/pyrol/pyrol/src/master/). I tried different ways and they all fail 

``pip3 install ROL==0.0.16``

``pip3 install ROL``

```
git clone git@bitbucket.org:pyrol/pyrol.git
cd pyrol
git submodule update --init
pip3 install -e .
```

I also tried to build this manually via 
```
git clone git@bitbucket.org:pyrol/pyrol.git
$ cd pyrol
$ python setup.py install
```

I don't have a problem with roltrilinos, I have Ubuntu 20.04.3 the latest version of pip3, CMake (3.27.4),  but I still get very weird installation errors. The log is very long so I printed into a LOG_FILE & attached here (sorry about that). If anyone has another way of installing ROL, and link it to the firedrake virtualenv I would really appreciate the help. Thanks!

[LOG_FILE.txt](https://github.com/icepack/icepack/files/12659254/LOG_FILE.txt)

**Comment by danshapero** [comment]
Hi Beatriz! I've been hitting the same problem. There's a fix which unfortunately requires some manual patching that I need to remember how to do. I'll get back to you in a few days with instructions. I'm a little slow lately because I'm on parental leave so apologies if it takes a bit.

**Comment by bearecinos** [comment]
many thanks @danshapero... not a problem there is no rush! 👍

**Comment by danshapero** [comment]
Can you open up a terminal, change directory to where you've cloned icepack, and do the following:

```
git remote add daniel https://github.com/danshapero/icepack.git
git checkout --track daniel/ROL
pip install -r requirements.txt
```

and copy/paste the output? Some things broke in both Trilinos and ROL. I had to fork and manually patch them both.

There are likely to be some other breakages if you've installed Firedrake very recently because they've made some changes to how the adjoint code works. I'll be fixing those in the next week or two, thanks for your patience in the meantime!

**Comment by bearecinos** [comment]
Thanks I managed to install ROL I will let you know if something else pops out while running the data assimilation notebook.
Cheers

**Comment by danshapero** [comment]
Perfect, I'll close this issue for now then. If you run into more problems, you might want to have a look at [this pull request](https://github.com/dolfin-adjoint/pyadjoint/pull/118) to pyadjoint, which updates it for some of the changes to the Firedrake API.
