### ISSUE TITLE
Evaluating velocities at depth with the hybrid model

### ISSUE THREAD

**Issue by bryanvriel** [icepack/icepack#128]
I would like to evaluate a velocity field defined in xyz/xz space at an arbitrary array of points within the modeling domain. However, I am a bit confused with the firedrake conventions when evaluating function spaces in the z-coordinate.

For example, in the hybrid flowband tutorial [here](https://icepack.github.io/notebooks/tutorials/06-hybrid-ice-stream-xz/), there is a description for resolving shear flow using a weighted depth average. Since the use of Lagrange polynomials as weighting functions was confusing to me, I naively thought I could just evaluate the velocity as:
```python
Nx = 500
Nz = 100

# Create list of points in xz-space to evaluate velocity field
x_grid = np.linspace(5.0e3, 30.0e3, Nx)
z_grid = np.linspace(0.0, 1.0, Nz)
Xg, Zg = np.meshgrid(x_grid, z_grid)
points = np.column_stack((Xg.ravel(), Zg.ravel()))
points = [tuple(pt) for pt in points]

# Run evaluation
u_grid = np.array(u(points)).reshape(Xg.shape)

# Make plot
fig, axes = plt.subplots()
axes.set_title("Shear component of ice velocity")
axes.set_ylabel("velocity (m / yr)")
firedrake.plot(u_shear, axes=axes);        # computed earlier in the notebook
axes.plot(x_grid, u_grid[-1] - u_grid[0])  # surface velocity minus base velocity
```
However, I find the evaluated velocities give me a (surface - base) difference that's about 3x larger than `u_shear`. Also, I found that firedrake allows me to evaluate `z_grid` in the domain `[-0.4, 1.4]`, which was surprising as I figured that $\zeta$ was only defined in `[0, 1]`.

Is there something I'm missing here? Is there a better way to reconstruct the velocities at depth?

**Comment by danshapero** [comment]
Hi Bryan! The code in that notebook to compute `u_shear` isn't evaluating the basal velocity as such, but rather the projection of the velocity field onto the 1st-degree Legendre polynomial, which is orthogonal to the constant functions. So it is to be expected that the basal velocity (or the surface - basal difference) is not the same as this projection.

The code that you've written certainly ought to work to compute the basal velocity. If you want something that will make a Function defined on the base mesh instead of a grid of values, you can also do this by a clever weighted depth-average. Let me know if that's what you need and I'll send some more complete code for it.

**Comment by bryanvriel** [comment]
Ah, thanks Daniel for clearing that up! The projection makes sense. Indeed, I think I could make use of a few examples of clever depth-average weighting. I was originally thinking of constructing delta functions centered at arbitrary depths, but I'm pretty sure I would've done that wrong!

**Comment by danshapero** [comment]
I made a branch with some demonstrations in the hybrid XZ notebook [here](https://github.com/danshapero/icepack/blob/surface-basal-velocity-demo/notebooks/tutorials/06-hybrid-ice-stream-xz.ipynb).
The important part is right before the conclusion section.
In case you don't want to go digging through all that, here's the code to calculate the basal and surface velocities and plot them:

```
import sympy

ξ = sympy.symbols("ξ", real=True)
legendre_polynomials = [sympy.legendre(n, 2 * ξ - 1) for n in range(3)]
basis_functions = [p / sympy.sqrt(sympy.integrate(p**2, (ξ, 0, 1))) for p in legendre_polynomials]
basal_values = [p.subs({ξ: 0}) for p in basis_functions]
surface_values = [p.subs({ξ: 1}) for p in basis_functions]
basal_polynomial = sum(w * p for w, p in zip(basal_values, basis_functions))
surface_polynomial = sum(w * p for w, p in zip(surface_values, basis_functions))
basal_weight = sympy.lambdify(ξ, basal_polynomial.simplify())(ζ)
surface_weight = sympy.lambdify(ξ, surface_polynomial.simplify())(ζ)
u_basal = icepack.depth_average(u, weight=basal_weight)
u_surface = icepack.depth_average(u, weight=surface_weight)

fig, axes = plt.subplots()
axes.set_title("Surface & basal velocities")
firedrake.plot(u_basal, edgecolor="tab:blue", label="basal", axes=axes)
firedrake.plot(u_surface, edgecolor="tab:red", label="surface", axes=axes)
axes.legend();
```

Does all the sympy + Legendre polynomial hackery here make sense?
You mentioned constructing delta functions at arbitrary depths.
This code is doing that by instead looking at the action of a delta function on something that we know has an expansion in Legendre polynomials.
So it does what a delta function would do without having to actually form the delta function as such.
In any case this should be probably either be in a tutorial or in icepack itself.
The attached figure shows the result.

![surface-basal-velocities](https://github.com/icepack/icepack/assets/3905742/ce1696e8-cd22-4f83-9e76-7c746131216b)

I am a little disturbed by the fact that you can evaluate things at negative values of the vertical coordinate -- arguably those should be giving a "point not in domain" error.
That's more of a Firedrake issue than an icepack issue.

Closing this for now, feel free to reopen if anything else is unclear.

**Comment by bryanvriel** [comment]
Many thanks Daniel, I think I understand now how the weights are interpreted with respect to a Legendre polynomial expansion. That's quite clever!

Yeah, I'm not too worried now about the out-of-domain evaluations. Perhaps firedrake is assuming that the user knows the vertical mesh is represented by a polynomial expansion and can thus technically be evaluated out of the domain. I'll just make sure never to do that.
