### ISSUE TITLE
change where measures (dx, ds) are applied

### ISSUE THREAD

**Issue by danshapero** [icepack/icepack#30]
Right now, every model class (IceShelf, IceStream, etc.) has methods to calculate parts of the action for the diagnostic physics. For example several models call out to [icepack.models.viscosity.viscosity_depth_averaged](https://github.com/icepack/icepack/blob/0d396e294f2a14d5b15c607e524bd81b03c97624/icepack/models/viscosity.py#L90) to calculate the viscous part of the action.

Each part of the action is either an integral over either the entire domain, in which case the integrand gets multiplied by the measure `dx`, or over the boundary, in which case the integrand gets multiplied by the measure `ds`. The method `action` creates a symbolic representation of these parts, adds them altogether, and returns the sum.

Instead, each part should return the integrand, and the `action` method should multiply by the right measure. The reason for this is that it becomes much easier to calculate, say, the internal viscous stress as the derivative of this part of the action. The use case for this change is to make the damage mechanics solver that @hoffmaao wrote more flexible. This change will make the process the same even when users substitute their own parameterization for the viscosity or other components, which isn't the case right now (see [here](https://github.com/icepack/icepack/blob/0d396e294f2a14d5b15c607e524bd81b03c97624/icepack/models/damage_transport.py#L104)). There are probably other physics models (e.g. a future calving model) that need to know the stress.

This change wouldn't actually alter what's being computed, just where the work happens. There will be a breaking change in the API for the damage solver, which would need to be initialized with the viscosity function. @hoffmaao any thoughts?

**Comment by hoffmaao** [comment]
@danshapero  This seems great! We should just change the documentation to focus new physics development around the kernel rather than the action.

**Comment by danshapero** [comment]
@hoffmaao I'm working on [this branch](https://github.com/danshapero/icepack/tree/measures) if you want to have a look. I think I've updated all the text in the docstrings and demos to reflect the changes but it's definitely important that everything is consistent.
