### ISSUE TITLE
separate models and solvers

### ISSUE THREAD

**Issue by danshapero** [icepack/icepack#31]
Right now the model classes use `firedrake.solve` instead of constructing reusable variational problem / solver objects. This is wasteful computationally, especially for the hybrid model.

On top of that, the model class is responsible both for specifying what problem you're solving as well as how you're solving it. By separating out the "how" into a separate class we can both eliminate the waste and improve the overall design.

The usage will look something like this:

    model = icepack.models.IceShelf()
    solver = model.create_solver(u=u, h=h, A=A, **opts)
    for step in range(num_timesteps):
        u = solver.diagnostic_solve(u=u, h=h, A=A)
        h = solver.prognostic_solve(dt, h=h, u=u, a=a, h_inflow=h_inflow)

There's one extra step, creating the solver object. There is one possible downside though. With the current design, you can do crazy things like using a P1 discretization for the thickness at one step and a P2 discretization at the next step. If all the input fields are getting cached, this would probably be an error. That's pretty obvious to the user, but there could be subtler issues of reference to out-of-date objects silently giving wrong results.

@hoffmaao , @jabadge thoughts?

**Comment by jabadge** [comment]
@danshapero With the separation of the problem specification and the solver, could one still use a different discretization for each step by creating multiple solvers? Or would this cause different problems?

**Comment by danshapero** [comment]
Yea you should definitely be able do that! Using a lower- and a higher-order discretization at the same time is actually a great way to decide how to refine the mesh.

**Comment by hoffmaao** [comment]
@danshapero @jabadge This is great! The variables reassigned during calls to the current Model objects include the mesh ids, the boundary conditions, the convex part of the action functional and the action functional itself, correct? Where does the marginal computational savings for the higher order model come from in the action definition (where viscosity friction, gravity etc. get defined), or is there another difference between the Hybrid vs SSA solve functions?

**Comment by danshapero** [comment]
@hoffmaao sorry I didn't reply to this earlier -- the savings aren't in forming functionals themselves but rather in linear solvers. When you solve a linear system -- whether it's for the next value of the ice thickness or to get a search direction in the nonlinear solve for the new ice velocity -- there's a whole bunch of work that can be reused on subsequent solves. For example, we're using a direct solver, where there's a high setup cost in computing the sparsity pattern of the factored matrix. Right now all that data is getting tossed out only to be recomputed again on every repeated solve and this is known to slow things down a lot. There's a similar issue with the Gauss-Newton inverse solver.

There isn't anything fundamentally different about the hybrid model, it's just a lot more expensive than a 2D model so you're more likely to notice the speedup. There are also big potential gains if you're clever about preconditioning the hybrid model solver; David suggested a multigrid-type approach to me at the SIAM meeting in February and I want to try that out.

I'm working on [this branch](https://github.com/danshapero/icepack/tree/solvers) if you want to have a look.
