### ISSUE TITLE
Bilinear Interpolation (specifically non NN interp) from Gridded Data Sets

### ISSUE THREAD

**Issue by fastice** [icepack/icepack#35]
icepack/interpolate.py https://github.com/icepack/icepack/blob/bda151d1a7b3b1377c9632eefc80828a9a6a0cec/icepack/interpolate.py#L53

This uses the rasterio NN interpolation. Would be good to have at least a bilinear (or other higher-order) interpolation option.

**Comment by danshapero** [comment]
Sure thing, we can implement this by doing a windowed read around the mesh and calling one of the functions in [scipy.interpolate](https://docs.scipy.org/doc/scipy/reference/interpolate.html). Bilinear interpolation is easy, cubic splines should be fine too.

The only problem I foresee is dealing with missing data. For bilinear this shouldn't be too much of a headache but I can see it getting more severe with higher-order interpolation.
