### ISSUE TITLE
more specific install/ update/ reinstall instructions (esp. for editors)

### ISSUE THREAD

**Issue by jabadge** [icepack/icepack#41]
In the documentation, it would be helpful to have install instructions for scenarios that are relevant to those who edit icepack. For example, someone who has been editing icepack needs to reinstall firedrake, but they don't want to reinstall icepack. What do they do?

**Comment by danshapero** [comment]
@jabadge Can you look at [this page](https://icepack.github.io/maintenance/) of the new website and tell me if that covers the scenarios you had in mind? I think it covers most of what you and I have discussed before but I'm happy to add more if you think it would help.

**Comment by jabadge** [comment]
@danshapero Thanks for putting it together! I think that covers most of what I needed reminding of each time I either had to reinstall firedrake or prepare to submit a pull request. For this line: pip3 install --editable ."[doc]", does this need to be done inside the icepack directory? If so, that would be helpful to say. Or is it the directory that "[doc]" is referring to?

**Comment by danshapero** [comment]
Yes it does, although I could change the `.` to something like `</path/to/icepack>` in which case the instructions would work regardless of where you were calling pip from. The "[doc]" flag is telling pip that you want to install the dependencies for building the documentation as well. It's part of a general mechanism pip has for dealing with optional dependencies. I'll add a note about why that's there too.

**Comment by jabadge** [comment]
That's good to know about the "[doc]" flag.

**Comment by danshapero** [comment]
K I've added your suggestions -- thanks for the input! I'm going to mark this as resolved by icepack/website@c2efd09aa80bda038eb79a3908747e76b0fb4a08. I'm still planning on adding an install troubleshooting guide but some of that content should go in the Firedrake documentation. Feel free to raise issues or make PRs on the website repo if you think there's more information we should put on there.
