### ISSUE TITLE
Functions for surface/bed value extraction

### ISSUE THREAD

**Issue by dlilien** [icepack/icepack#96]
Perhaps I am just missing it, but is there an easy way to extract values on the surface or bed that is compatible with Firedrake adjoint? I'd like to do inversions with `HybridModel`, and so need to define the loss functional just at the surface. As of now, if I just do this the naive way and define the loss functional by subtracting observations and model, I compare the depth-averaged velocity to the observations. I tried extraction using the following
```
def extract_surface(q_in):
    mesh_x = q_in.ufl_domain()._base_mesh
    shape = q_in.ufl_shape
    if len(shape) == 0:
        VLin = firedrake.FunctionSpace(
            q_in.ufl_domain(), "CG", 2, vfamily="CG", vdegree=1
        )
        q_targ = firedrake.interpolate(q_in, VLin)
        element_xz = q_targ.ufl_element()
        element_x = element_xz.sub_elements()[0]
    else:
        VLin = firedrake.VectorFunctionSpace(
            q_in.ufl_domain(), "CG", 2, dim=shape[0], vfamily="CG", vdegree=1
        )
        q_targ = firedrake.interpolate(q_in, VLin)
        element_xz = q_targ.ufl_element()
        element_xy = element_xz.sub_elements()[0].sub_elements()[0]
        element_x = firedrake.VectorElement(element_xy, dim=shape[0])

    Q_x = firedrake.FunctionSpace(mesh_x, element_x)
    q_x = firedrake.Function(Q_x)
    if len(shape) > 0:
        q_x.dat.data[:] = q_targ.dat.data[1::2, :]
    else:
        q_x.dat.data[:] = q_targ.dat.data[1::2]
    return q_x
```
but this is breaking the inversions (I think since overriding the data screws up the adjoint tape).

I also tried defining a 2d mesh in 3d space and interpolating from the 3d function space, but that produced errors around needing a VertexOnlyMesh.

Is there a solution here that I am missing, or a suggestion on how to proceed?

**Comment by danshapero** [comment]
Would it work to do something like this:

```python
J = inner(u - u_obs, u - u_obs) * ds_t
```

to define the loss functional? Using `ds_t` will integrate just over the top surface, likewise `ds_b` for the bottom.

**Comment by dlilien** [comment]
Yes, this works perfectly. Totally missed this section on the Firedrake documentation.
